# Generated by Django 4.2.4 on 2023-08-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(default=models.FloatField(default=0.0)),
        ),
    ]
