# Generated by Django 4.2.4 on 2023-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home'), ('toys', 'Toys'), ('sports', 'Sports'), ('food', 'Food'), ('art', 'Art'), ('jewelry', 'Jewelry'), ('automotive', 'Automotive'), ('real-estate', 'Real Estate')], max_length=100),
        ),
    ]
