# Generated by Django 4.2.4 on 2023-08-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default='No description provided', max_length=1000),
        ),
    ]
