# Generated by Django 4.2.4 on 2023-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Home', 'Home'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Food', 'Food'), ('Art', 'Art'), ('Jewelry', 'Jewelry'), ('Automotive', 'Automotive'), ('Real-estate', 'Real Estate')], max_length=100),
        ),
    ]
