# Generated by Django 4.2.4 on 2023-08-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_user_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='watchlist',
        ),
    ]
